
#Redis
spring:
  redis:
    port: 6379
    host: localhost


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.coffeeandit.transactionbff.controllers
  
limits:
  url: http://localhost:8081

